# Generated by Django 5.0.5 on 2024-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='is_remote',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On-site')], default='on-site', max_length=10),
        ),
    ]
