# Generated by Django 5.0.5 on 2024-05-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joboffer_is_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='education_required',
            field=models.CharField(choices=[('no-education', 'No-Education'), ('high-school-degree', 'High School Degree'), ('associate-degree', 'Associate Degree'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('doctoral', 'Doctoral')], default='no-education', max_length=50),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('seasonal', 'Seasonal')], default='full-time', max_length=10),
        ),
    ]
