# Generated by Django 5.0.4 on 2024-05-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joboffer_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=50, unique=True)),
                ('search_count', models.IntegerField(default=1)),
            ],
        ),
    ]
