# Generated by Django 5.0.4 on 2024-05-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_joboffersearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffersearch',
            old_name='search_count',
            new_name='lookup_count',
        ),
    ]
