# Generated by Django 5.0.4 on 2024-05-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_description_alter_company_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
