# Generated by Django 5.0.4 on 2024-05-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_img_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
