# Generated by Django 5.0.4 on 2024-05-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_cover_img_url_company_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='premium',
            new_name='is_premium',
        ),
    ]
