# Generated by Django 5.0.4 on 2024-05-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_company_cover_img_url_remove_company_logo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_img_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
