# Generated by Django 5.0.4 on 2024-05-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_cover_image_remove_company_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cover_img_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
